### ISSUE TITLE
Braille display is one cursor after sound pitch

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#1]
The braille display works nicely. Great job! The only issue I have found is that the braille cursor locations are not precisely coupled with its corresponding sound pitches. When I press left and right arrows, cursor location moves along with braille columns. However, this cursor location is one column after its corresponding sound. For example, The highest tone/y_value in our sample svg file is at the far right. This pattern is also represented in braille unicode, but I here the highest tone when my braille cursor is one column after the target location.

**Comment by yujuny2** [comment]
I have fixed the cursor so that the bar chart is aligned with the braille display. It is updated in the repo now. Please tell me if there is any other issue with it.
