### ISSUE TITLE
[Scatterplot]: Speed-up function is not working as intended

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#101]
## Reproducible Steps

1. Open scatterplot.html

1. Go to the far left by pressing Ctrl+LeftArrow.

1. Make sure your sonification mode is "combined" mode.

1. Start autoplay by pressing Ctrl+Shift+RightArrow key.

1. As soon as the autoplay starts, keep pressing period (`.`) key multiple times to speed up.

## Current Issue

Autoplay stops when it gets faster and faster.

## Expected Behaviors

Speed-up function should be working in a stable manner when autoplayed.

**Comment by yujuny2** [comment]
@jooyoungseo This happens because I haven't adjusted the autoplay-points rate. It works properly now. Thanks.
