### ISSUE TITLE
Boxplot horizontal: group info is not displayed in terse mode

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#111]
Thanks for making the horizontal boxplots!

Currently, I don't hear group label when switching groups by pressing Up/DownArrows in horizontal boxplots. Instead, I hear redundant group labels when using Left/RightArrows. Please test with sonification on and terse mode for both tutorial and task boxplot (horizontal).

**Comment by ellvix** [comment]
Too much spaghetti, did a full rewrite on boxplot text display
