### ISSUE TITLE
Help Menu Close Issues

### ISSUE THREAD

**Issue by yilinxia** [xability/maidr-legacy#113]
can we possibly enable second press close the help menu?

**Comment by jooyoungseo** [comment]
@ellvix Actually, it used to work, but I verified that pressing "H" key does not close the help menu.

**Comment by ellvix** [comment]
I've 'fixed' this, but I don't really agree. The menu contains headings and is not within the role application area. I think we should just use Esc to close the menu.

**Comment by jooyoungseo** [comment]
@ellvix -- Aw, that's a really great point that I mistakenly neglected! @yilinxia and I got confused and reported this issue b/c "H" key used to work like a toggle key previously. @ellvix -- Then, Could we go with what you suggest? @yilinxia -- We can revise our Google Doc (something like ... to close help menu, press "ESC" key).

**Comment by ellvix** [comment]
Done, it's now ESC
