### ISSUE TITLE
Heatmap Terse Mode

### ISSUE THREAD

**Issue by yilinxia** [xability/maidr-legacy#114]
I found that the terse mode for the current heatmap shows “Chinstrap, 0” . do we need involve the x-axis and let it become something like “Chinstrap, Biscoe, 0"? @jooyoungseo

**Comment by jooyoungseo** [comment]
@yilinxia This is an intended behavior. When you navigate cell row-by-row, our system does not display column header label b/c users remain in the same column. Similarly, our system does not display row header labels when users navigate left-to-right or right-to-left b/c users remain in the same row. Please reopen this issue if you think this is not the case that you highlighted.

**Comment by yilinxia** [comment]
Hi Jooyoung @jooyoungseo , yeah, so my understanding is that if the label did not change, we wont include the label. But right now, the label stays always the same. For example, if we navigate with a row, the row label should be ignitied and users should get the column label.

**Comment by jooyoungseo** [comment]
@yujuny2 -- Please test and fix tutorial and task heatmap with terse mode. I have verified that the column labels and row label announcements are reversed. You will u understand what @yilinxia means once you test them on your end.

**Comment by yujuny2** [comment]
@jooyoungseo @yilinxia I don't know why but the variables get changed for some reason. Anyways it's fixed now.
