### ISSUE TITLE
Scatterplot: Verbose mode in smoothed line layer displays undefined type

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#118]
1. Open either tutorial or task scatterplot.

1. PageUp to focus in the second (smoothed line) layer.

1. Press B to activate braille.

1. Press T to activate verbose mode.

1. Press Left/RightArrows.

* Note: You will find undefined types.

We need to fix this as something like "Gradient is xxx." Feel free to be creative in using any wording for the verbose mode because you have come up with this gradient feature.

**Comment by yujuny2** [comment]
@jooyoungseo Do you mean that displaying the value of the current point of the line anymore? Currently, I have fixed the verbose text to be what you've mentioned. Please tell me if you think the verbose text can be improved further. Thanks.
