### ISSUE TITLE
Scatterplot: Support Ctrl+Home and Ctrl+End in point layer braille

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#121]
Given that point layer braille needs to be scrolled through, we need to make Ctrl+Home and Ctrl+End (going to the starting and ending point) work.

1. Open either tutorial or task scatterplot.

1. In point layer, press B to activate braille mode.

1. Try with Ctrl+Home and Ctrl+End to go to the first and end.

* Note: This does not work.

**Comment by yujuny2** [comment]
@jooyoungseo Braille navigation is currently disabled in the point layer because the braille characters represent the points in the line layer. Do you want to activate braille navigation in the point layer?

**Comment by jooyoungseo** [comment]
@yujuny2 -- Yes, please do. this is because the display area needs a lot of scrolling behavior depending on the column size and we would like to give users to some cursor controls to quickly jump to the beginning and end of the display.

**Comment by yujuny2** [comment]
@jooyoungseo They can actually do it in the point layer. We support that in the svg section. If I enable braille navigation in the point layer, the braille and the visual points won't be in sync.

**Comment by yujuny2** [comment]
@jooyoungseo What I mean is that even if the user can jump to the beginning and the end, they are actually navigating two different components -- braille for line, and svg for points.

I'll implement it. We can see if it's better to have this functionality enabled.
