### ISSUE TITLE
Critical bug: boxplot task (horizontal) does not give group label in terse mode

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#122]
Just try out with task boxplot (horizontal) in terse mode and verbose mode. You will figure out what I am talking about right off the bat.

**Comment by ellvix** [comment]
Not quite sure what you mean here actually. From what I understand it follows the design doc perfectly. The goal is to have text like "class is subcompact" moving one way, and "hwy is X" moving the other. But we don't have any labels there, so we just have "hwy". 

Can you rewrite the design doc or state required behavior here?

**Comment by jooyoungseo** [comment]
@ellvix -- Please try with  a horizontal task boxplot. In terse mode, it still does not give you a group label, such as continent name, when you move up and down.

**Comment by ellvix** [comment]
Ah I see. This is a separate bug. There was bad data passed in manually.
