### ISSUE TITLE
Critical bug: boxplot vertical terse mode provides redundant x label.

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#123]
Found in both tutorial and task (boxplot vertical):

1. Open boxplot vertical tutorial or task.

1. Press T to activate terse mode.

1. Press LeftArrow and RightArrow to switch groups in the current statistic.

## Current Behavior

Current stat which remains the same across the group is redundantly announced along with the group label.

## Expected Behavior

Only group label needs to be announced.

**Comment by ellvix** [comment]
Ooh good catch. I did that on purpose and I have no idea why.
