### ISSUE TITLE
Changing stat terms does not work

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#124]
I have  updated the boxplot stat term again: low -> minimum; high -> maximum. Unfortunately, it does not take any effect. Please take a look at my commit 38f9b2e and fix this issue if possible.

**Comment by ellvix** [comment]
Figured it out. I had stupidly hard coded those strings into the manual data input. They've been replaced with identifiers and not only does the whole system work, but we avoided a critical bug that would have happened if we changed resource files partway through .
