### ISSUE TITLE
Critical bug: boxplot maximum is empty

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#126]
1. Open tutorial boxplot (vertical).

1. Turn on terse mode.

1. Move around your arro keys to focus in maximum of 2seater group.

* Note: That's currently empty.

**Comment by ellvix** [comment]
Yep, that's expected. I used to have the word 'empty' in there, but you said remove it. Should we put it back?

**Comment by jooyoungseo** [comment]
@ellvix No, that's for outliers. Maximum always exists. Please check whether the data was missing.

**Comment by ellvix** [comment]
Yep, data missing. Want to redo that svg?

**Comment by jooyoungseo** [comment]
@ellvix The raw data is the same as the horizontal boxplot task. Do you need the raw data again?
