### ISSUE TITLE
Log tracker: no data info when text is off

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#148]
Current approach relies on text mode display, resulting in no data info when text mode is off. A reliable solution is needed that does not depend on user's current text mode. A virtual buffer can be used to create an invisible text only for a log tracker; however, we want to minimize any unnecessary overhead.

**Comment by ellvix** [comment]
I think I fixed this and forgot to close it last week. I currently output x and y label in full, @jooyoungseo let me know if the issue remains.
