### ISSUE TITLE
Log tracker: sonification property needs to be a string value

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#149]
Unlike text and braille modes, sonification property is denoted with numeric data type. This needs to be replaced with string values that reflect user's current sonification mode, such as "off," "on," "separate," and "combined."

**Comment by ellvix** [comment]
Fixed. I redid how we track sonification mode. We used 2 vars which was very annoying, replaced with just one: `constants.sonifMode`
