### ISSUE TITLE
Boxplot: Alt+Shift+Arrows does not work

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#150]
While Ctrl+Shift+Arrow keys work in boxplot, Alt+Shift+Arrows (incoming autoplay) does not work. Tested with task 3 boxplot (horizontal).

**Comment by ellvix** [comment]
Autoplay was significantly messed up. Braille especially. It didn't work at all, not even ctrl shift arrow keys. Rewrote most of it, we're good.
