### ISSUE TITLE
Critical bug in boxplot sonification: previous sound overlaps with the current one with a quick switch

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#153]
1. Open `task3_boxplot_horizontal.html`

1. Turn on sonification.

1. Focus in lower outlier area of Europe.

1. Press up key and down key quickly multiple times and hear how the empty lower outlier of Oceania is played.

* Note: The empty lower outlier sound is affected by the previous sound. You don't have this issue when you wait for the previous play to be finished though.

**Comment by ellvix** [comment]
Good catch @jooyoungseo ! We never bothered to stop previous tones when the next played. Added that, now we're good.
