### ISSUE TITLE
Add lx, ly, lt, and lf shortcut keys as sequential press

### ISSUE THREAD

**Issue by yujuny2** [xability/maidr-legacy#161]
As stated in title.

**Comment by yujuny2** [comment]
@jooyoungseo I have implemented these as sequential key presses. There are a few things I would like to double check with you:

1. Currently I have fixed a 2-second interval between the 'L' prefix and its subsequent keys (x, y, t, or f) such that after 2 seconds 'L' key is pressed, if there is no following key detected, the fact that 'L' key being pressed will be forgotten and the user has to press 'L' again before proceeding. I thought this would be better to avoid cases like this -- the user forgot or accidentally presses the 'L' key, and then proceeds with 'T' key, which gives them the title when what they want is switching text mode. I wonder if this is okay and if it is, is 2 second as an interval okay?

2. Within that 2-second interval after 'L' key is pressed, if any key other than x, y, t, or f is pressed, the 'L' key is still valid, and if x, y, t, or f is pressed within that 2 second, things still work. Do you want to invalidate 'L' after other keys were pressed or is my current implementation okay?

**Comment by jooyoungseo** [comment]
@yujuny2 

1. Yes for question 1. Could we add the key wait interval in the advanced user setting with 2 seconds as default value?

2. Let's completely cancel L command in case users press any invalid key other than X, Y, T, and F.
