### ISSUE TITLE
Braille boxplot cursor location

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#174]
cursor location for 75 and max doesn't line up with the data point. Cause is that these are ranges, and the actual point value comes on the wrong side. I need to write an exception to put the cursor on the other side for those

**Comment by ellvix** [comment]
Trying to fix, what's the goal here? Currently the cursor comes just before each thing (outlier, min, middle, 75, etc)

**Comment by jooyoungseo** [comment]
CC @yilinxia Please provide further context here.

**Comment by yilinxia** [comment]
Hi @ellvix, let me try to explain. The major problem is the max, others looks fine to me. 
When we tried to explain the maximum, we usually will say it is a point located on the **right side** of the right whisker. Right now, the cursor to show maximun is located on the **left side** of the right whisker, which is confusing. However, we also want to use the same cursor location to show upper outliers, which become difficult.

**Comment by ellvix** [comment]
@yilinxia I'm not sure what we need to do here. Currently the cursor is just before any section (ie, left side). We can move it, but we want consistancy. If we move the cursor to the right side for Max, we'd also want it on the right side for everything right of the middle line (75%, Max, upper outliers) otherwise cursor would be in the same place for 2 sections. Is that what you want?

**Comment by yilinxia** [comment]
@ellvix I prefer to stay what it is right now : ) PS: One crazy idea i have is that if we change the cursor (maximum only) to the right side of the right whisker, we can add a empty cell between the outlier and the whiskerto make sure that the cursor will move then participants can distinguish upper outlier and maximum

**Comment by ellvix** [comment]
Great, closing issue for now.
