### ISSUE TITLE
Visual highlighting graceful fail

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#189]
all chart types need to be tested so they gracefully fail if `madir.elements` is not supplied. Did barchart already but the rest need a look

**Comment by yujuny2** [comment]
Done with barplot. Summary of how it works:
absent data --> will not work at all
absent x level, data.length != elements.length --> no visual highlighting, warning
absent elements --> no visual highlighting
absent elements, data.length != xlevel.length --> no visual highlighting, warning
absent x level, absent elements --> no visual highlighting

**Comment by yujuny2** [comment]
update: add warnings for any absent elements

**Comment by yujuny2** [comment]
For heatmap -- Need to fix display.js as the text won't work with the absence of x level or y level.

**Comment by ellvix** [comment]
Addition: Handle 'Fill' for all plots (should work for heatmap if it exists, or "Plot does not have a Fill label" fallback)

**Comment by yujuny2** [comment]
Heatmap:
- throw error if 'data' is not defined
- turn off visual highlight if 'elements' or 'xlevel' or 'ylevel' is absent
- turn off visual highlight if elements.length != data.length
- fixed fill label key (L+F)
- replace x_labels/xlevel, y_labels/ylevel with undefined values if absent

**Comment by yujuny2** [comment]
Boxplot, lineplot:
- turn off visual highlight when 'elements' is absent

**Comment by yujuny2** [comment]
Scatterplot:
turn off visual highlight if type 'point' or 'smooth' exists, and
- 'elements' does not exist at all
- 'elements' exists but is empty
- 'elements' exists but is not an array
- 'elements' and 'type' do not have the same length

**Comment by yujuny2** [comment]
Histogram:
- turn off visual highlight if 'elements' is absent
- turn off visual highlight if 'elements' and 'data' do not have the same length
