### ISSUE TITLE
Add event handler to svg object instead of window

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#2]
Currently, all the keydown events and their corresponding event handlerss are bound to `window` object. This is a great start. However, what if there are more than one svg objects contained in the current web page? `addEventListener()` will be triggered against when the whole browser window is loaded. Probably, a better approach would be binding these events and handlers to `svg` object unit instead of the `window` object. This way would allow users to interact with any number of svg objects in the current window.

**Comment by ellvix** [comment]
Event handlers are now properly scoped. Some to svg, some to window, some to braille input, etc
