### ISSUE TITLE
Move legend maidr json schema inside axes as label

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#223]
In the following schema, we need to change the lengend to label (plus, we need to add fill-label which is currently missing and pulling from SVG):

https://github.com/uiuc-ischool-accessible-computing-lab/MAIDR/blob/dbc9d9d90088cdcb8247879519970d87e1443eb4/user_study_pilot/task2_heatmap.html#L1625-L1626

**Comment by ellvix** [comment]
axes: {
          x: {
            label: 'Engine Displacement',
          },
          y: {
            label: 'Highway Mileage',
          },
        },

instead of top level legend_x: "year"

This may already be working, so make sure system is pulling from the correct spot

**Comment by ellvix** [comment]
also need an option for the following top level schema (`maidr.labels`):

`labels: { x: "year", y: "countries", fill: "gdp", title: "title of graph", caption: "chart caption here", subtitle: "subtitle" }`

**Comment by ellvix** [comment]
This is a second option for labeling. This will be the primary source, so it overwrites any duplicates (like `maidr.title` or `maidr.axes.y.label`)

**Comment by ellvix** [comment]
Some background info

- title: the main title of the chart
- subtitle: extra info that supplements the title
- caption: source info for the chart

Different than `name`, which is literally our own hack for aria-live on initial focus. Change `name` to `on_focus_announcement`.

**Comment by ellvix** [comment]
all label info need to be usable by LX method (eg, LT for title, LC for caption, etc).
