### ISSUE TITLE
Support stacked normalized bar plot

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#259]
Also high priority: After adding stacked bar plot, please support this plot: https://github.com/uiuc-ischool-accessible-computing-lab/MAIDR/blob/3a9586eb962f877d055262c28e7e26df7aa45364/stacked_normalized_bar

**Comment by ellvix** [comment]
Controls: similar to heatmap etc. Up down moves between levels, right left between bars. 

Sonification: 

On individual levels, play single (unique, use sine / triangle / etc) tone. Then also have total tone available (sum of everything, like the top of the visual bar). Then also have 'all', where all raw values are played.
