### ISSUE TITLE
Replace boxpot stat values with exact ones

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#27]
Currently, we obtain boxplot stat values from svg object. However, we may want to use exact values exported from R back end: `boxplot_data.json`

**Comment by ellvix** [comment]
This will be a lot of effort, we may want to prioritize other new features like help and research tracking first

**Comment by jooyoungseo** [comment]
Related to #70.

**Comment by ellvix** [comment]
This was completed when we moved to manual input
