### ISSUE TITLE
Better word choices for boxplot stats

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#29]
CC @ellvix and @yilinxia

I suggest we reword the following terms in boxplot:

1. `Minimum` -> `Low`

2. `Maximum` -> `High`

This is because these terms are misleading. The ending points of left and right wiskers actually are not matched with data min and max values.

Here is a formula how low and high (i.e., the ending point of both wiskers) values are calculated:

* High: $(IQR * 1.5) + Q3$

* Low: $(IQR * 1.5) - Q1$

Outliers are any values outside either low or high  values.

**Comment by ellvix** [comment]
Better yet, we should put all text we're using in resource files. Partially so that we can better update (rather than searching codebase for these terms), and partially so that we can more easily apply translations later

**Comment by jooyoungseo** [comment]
@ellvix  -- Yea, we would like to customize the wording depending on users' background knowledge, such as choices between Q1 and 25%, etc. Also would love to translate into other languages just like what you said.

**Comment by ellvix** [comment]
Created resource file, just did these boxplot changes for now but it's all set up for l10n and better string management later
