### ISSUE TITLE
Add restful api and endpoint

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#304]
# Feature Request

## Description

We need to create a restful api and [open api spec](https://github.com/OAI/OpenAPI-Specification) for the maidr rendering process.

Possible use cases are:

1. ChatGPT Plus user upload any maidr-supported plots.

2. Ask ChatGPT to make this plot accessible with maidr.

3. ChatGPT analyzes the plot and automatically completes the maidr-compliant json schema: [This requires some experiment. Just conceptually understand this step, and let's focus on the next steps.]

4. ChatGPT sends a request to our endpoint.

5. Our endpoint returns the working maidr page url.

## Motivation

This is an prerequisite to create a ChatGPT plug-in and custom GPTs. Just FYI, ChatGPT and custom GPTs are two separate, but similar features, which are only available for ChatGPT Plus paid version.

## Proposed Solution

You can expand this simple OpenAPI schema example:

```yaml
openapi: 3.0.0
info:
  title: Maidr API
  version: 1.0.0
  description: API for processing a maidr object along with an SVG image and returning a rendered webpage URL

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /maidr:
    post:
      summary: Process a maidr object and an SVG image, and return a webpage URL
      description: Receives a maidr object and an SVG image, processes them, and returns a URL to a rendered webpage
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                maidr:
                  type: string
                  description: The maidr object in JSON format
                image:
                  type: string
                  format: binary
                  description: The SVG image file
      responses:
        '200':
          description: Webpage URL where the maidr object and image are rendered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderedWebpageResponse'
        '400':
          description: Invalid input
        '415':
          description: Unsupported media type

components:
  schemas:
    RenderedWebpageResponse:
      type: object
      properties:
        message:
          type: string
          description: Confirmation message
        webpageUrl:
          type: string
          format: uri
          description: URL of the rendered webpage
```

- [x] Create a single endpoint.

- [x] Take a post method call: maidr json object along with its corresponding svg.

- [x] Response: url of rendered html file containing the json schema and svg.

- [x] Host a maidr endpoint as a serverless function on Azure cloud.

## Additional Context

Please read how OpenAPI spec can be used in ChatGPT plugin and custom GPTs builder:

- [Custom GPT builder with OpenAPI spec](https://alexsniffin.medium.com/building-an-openai-gpt-with-your-api-a-step-by-step-guide-70168bef00e7)

- [ChatGPT Plugin with OpenAPI spec](https://apidog.com/articles/chatgpt-plugins-open-api/)

## Checklist

- [x] I have searched for similar feature requests and confirmed that this is a new request.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the motivation behind this feature request.
- [x] I have outlined a proposed solution or ideas for implementing this feature.
- [x] I have provided any additional context or screenshots if applicable.

**Comment by sandeep-ps** [comment]
I have started exploring the OpenAI API and potential frameworks for developing the web service. Fast API (Python) is potentially a good candidate (https://fastapi.tiangolo.com/#performance). Previously, I have used Flask and Connexion. I know that you have shared Express as another option. I will also look into it. 

Please let me know if we have access to the Plus subscription through the university. Currently, I am waitlisted for its access through my personal OpenAI account.

**Comment by jooyoungseo** [comment]
@sandeep-ps -- Yes, let's go with fastapi. It is easy to deploy to Azure cloud using VSCode:

https://learn.microsoft.com/en-us/samples/azure-samples/fastapi-on-azure-functions/azure-functions-python-create-fastapi-app/

We currently don't have the ChatGPT Plus account on our team level, and we will have to use our personal account to test until my purchase request gets approved.

The official ChatGPT page says:

> Update. We are no longer accepting new Plugins, builders can now create Actions inside of a GPT.

We will have to use GPTs builder instead of the plugin.

**Comment by jooyoungseo** [comment]
@sandeep-ps -- We have the access to Azure cloud on team level. I will ask around how to add you under my account.

**Comment by sandeep-ps** [comment]
Thanks. 

Based on today's team discussion, the endpoint will need to respond with generated HTML content (and not URL).

**Comment by sandeep-ps** [comment]
MAIDR API with the required endpoint has been created and deployed. The response is HTML content, and the deployment uses Azure Container Services. This issue can be closed. Thanks.

**Comment by sandeep-ps** [comment]
Closing as complete. Please feel free to re-open this issue if needed. Thanks.
