### ISSUE TITLE
Make maidr logo

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#313]
We need to create a maidr logo with the following ideas in mind:

- Multimodalities: touchable, audible, visible, and conversational
- Accessible data exploration
- logo format: png and svg

@SK-143381 Please create some sample logo and share it with us on Slack.

**Comment by jooyoungseo** [comment]
@SK-143381 Please make a PR for this ticket.

**Comment by SK-143381** [comment]
I created the PR, but am not able to link it to this issue. Logo #357 is the PR.
