### ISSUE TITLE
[BUG] B,T,S modes don't work on Matplotlib generated svg files 

### ISSUE THREAD

**Issue by SK-143381** [xability/maidr-legacy#315]
# Bug Report

## Description
The svg file when created by matplotlib does not seem compatible with maidr when embedded into the html

## Steps to Reproduce
1. Step 1: Produce the svg file using matplotlib
2. Step 2: add the svg into the html, modify id, and change the variables based on inspecting the svg.
3. Step 3: add the paths to the maidr.js and the stylesheet
4. Step 4: modify var maidr to include the data points

## Expected Behavior
The b, t, s modes should have started working on the graph.

## Actual Behavior
The svg file gets selected, but the modes' functions are not working.

## Environment
- Operating System: Windows 11
- Browser: Chrome

## Additional Information
I have rechecked the paths of the sheets and added the id

**Comment by ellvix** [comment]
I don't have access to matplotlib, @SK-143381 do you mind providing the html file?

**Comment by ellvix** [comment]
Examples in 'example' branch, example folder.

**Comment by ellvix** [comment]
Following up on this, all issues seem to have been resolved by other fixes and all files in /examples/matplotlib work perfectly in all 3 B,T,S modes. 

@SK-143381 please verify and close this issue if all is good.

**Comment by SK-143381** [comment]
Everything works well.
