### ISSUE TITLE
Support Braille cursor routing

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#318]
We need to support braille cursor routing. This is a feature that allows the user to route the braille cursor to the PC cursor. A successful model is [Spark Braille](https://fizzstudio.github.io/sparkbraille/). They also have an open-source GitHub repository [here](https://github.com/fizzstudio/sparkbraille). We can learn from their implementation.

**Comment by ellvix** [comment]
Just the actual tethering is needed, though we can look at the 2 column patterns and try to implement later, like for line plot. 

For now we just need the connection for the physical buttons on the braille display.

**Comment by ellvix** [comment]
fixed with PR #509
