### ISSUE TITLE
[FEAT] Create examples of lineplot from Matplotlib/Seaborn

### ISSUE THREAD

**Issue by saaivenk** [xability/maidr-legacy#353]
# Feature Request

## Description
Create examples from Matplotlib for line plots

## Motivation
Since the core library is tight-fitted for SVGs from ggplot2, we need to explore more with SVGs from other libraries like Matplotlib & Seaborn

## Proposed Solution
Create at least one sample for the following plots
 - line plot

## Checklist

- [x] I have searched for similar feature requests and confirmed that this is a new request.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the motivation behind this feature request.
- [x] I have outlined a proposed solution or ideas for implementing this feature.
- [ ] I have provided any additional context or screenshots if applicable.

**Comment by jooyoungseo** [comment]
@SaaiVenkat The example does not work. Please patch the PR again after you test BTS manually.

**Comment by saaivenk** [comment]
@jooyoungseo As previously mentioned in the [PR additional notes](https://github.com/uiuc-ischool-accessible-computing-lab/maidr/pull/354), the example won't work because the patch was ready, but was not yet merged. I'll merge the patch first and then close this issue.
