### ISSUE TITLE
[Boxplot] Redundant group label is spoken even in terse mode when braille is on

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#42]
## Reproducible Steps

1. Load NVDA or any screen reader.
1. Launch `boxplot.html`.
1. Tab to focus on the svg area.
1. In terse mode, move your point by pressing left and right arrows: You don't hear group label, which is correct.
1. This time, however, press `b` to activate braille mode and do the same thing (pressing left or right arrows): You would hear redundant group label even though it's still in terse mode.BB

**Comment by ellvix** [comment]
duplicate issue
