### ISSUE TITLE
feat: Make LLM aware of user position

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#421]
Like, what data point they're on, where in the chart.

**Comment by ellvix** [comment]
Will need to adjust data to be read easier by LLM. For example, position = 3 makes sense on a bar chart and the LLM could probably pick it up, but position = 2, 4 on boxplot doesn't make any sense and needs to be translated to '2nd plot from the top, on midpoint'.

**Comment by ellvix** [comment]
This will need to be sent every time the user opens the window, which defeats the whole purpose of loading in advance as they'd need to wait. Suggestion: only send user position if user asks an actual question. Should we add on every user question, or track when the position updates and only update the LLM once?

**Comment by jooyoungseo** [comment]
@ellvix Wonderful! Probably, we can send the "verbose" text buffer info along with the json schema to LLM for the current cursor position?

**Comment by ellvix** [comment]
Try: Send verbose text behind the scenes. Message is "Here is the current position in the chart, no response needed, please use this info only if it's relevent to future questions: [verbose text]". Neither the message nor response is logged and shown to user.
