### ISSUE TITLE
fix: LF not working on heatmap

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#431]

**Comment by ellvix** [comment]
Can't reproduce. Likely this was fixed with unrelated code, but @jooyoungseo can you or someone else confirm?

**Comment by jooyoungseo** [comment]
@ellvix  Please try with LF (label for fill)

**Comment by ellvix** [comment]
@jooyoungseo ahh thanks, it helps if I read the instructions properly haha

**Comment by ellvix** [comment]
Issue was that it was never added in the first place
