### ISSUE TITLE
Generalize autoplay speed controls for all graph types

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#44]
Currently, the autoplay speed controls (faster and slower) only work for scatterplot; however, please make this work for all types of graphs we support.

Also, please replace the current shortcut keys with the following:

* Faster: period key (.)

* Slower: comma key (,)

**Comment by ellvix** [comment]
@yujuny2 we're starting to have a lot of repeated controls and we're going to have more. I think we should do a more global keyboard eventlistener (probably in constants.js since that's always all plots), put these controls in there, and then anything else that's global (like B T S, etc)

**Comment by yujuny2** [comment]
I have added those functions in constants.js. It works for barplot, boxplot, and heatmap. Please tell me if there is any problem.
