### ISSUE TITLE
fix(LLM): remove redundant and outdated models

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#508]
In LLM UI, we have OpenAI Vision and OpenAI; Gemini vision and Gemini (in  total 4). Please remove redundant two not working sessions:

![image](https://github.com/xability/maidr/assets/19754711/a8174d97-935d-465e-9cfb-f664bb7c048a)

**Comment by ellvix** [comment]
issue confirmed, output contains duplicate error LLM responses

**Comment by ellvix** [comment]
@jooyoungseo can you confirm the issue? I saw the issue at our Wednesday morning meeting, and now it's just gone. I changed nothing and can no longer trigger the issue.
