### ISSUE TITLE
fix(scatterplot): address an issue where points remain highlighted even after maidr is deactivated

### ISSUE THREAD

**Issue by krishnanand5** [xability/maidr-legacy#527]
# Bug Report

## Description

On a scatterplot, when we navigate through it, points are highlighted based on the direction we navigate the plot. When maidr is deactivated on the plot, the last highlighted plot points remain highlighted and the plot does not return to its original state. This is residual from the invocation of maidr on the plot and should be removed when maidr is deactivated.

A follow-up scenario for the same is based on autoplay. If autoplay was in action when maidr was deactivated, the last highlighted plot points remain highlighted but when maidr is re-activated on the plot, autoplay immediately resumes from the left extreme of the plot autonomously.

## Steps to Reproduce

1. Open a scatterplot example
2. Navigate through the plot and deactivate maidr with some plot points highlighted on the screen.
3. The highlighted plots points remain highlighted whereas maidr has been deactivated, thus resulting in residual elements on the user interface.
4. For the autoplay scenario, activate autoplay and deactivate maidr when autoplay is in action.
5. If maidr is activated again, autoplay immediately starts from the extreme left without the user having started autoplay.

## Actual Behavior
Highlighted points remain highlighted and autoplay is functioning autonomously if maidr is deactivated when autoplay is running.

## Expected Behavior
When maidr is deactivated, the highlighting components (in the case of scatterplots, circle) should be removed and if autoplay was running, it should be killed before maidr components are destroyed.

## Screenshots
In this screenshot of a scatterplot example, certain points on the plot are highlighted eventhough maidr is inactive.
<img width="1087" alt="scatter_active" src="https://github.com/user-attachments/assets/4e8a5e1c-1824-4f2e-9256-7a14a72a3834">

## Environment
- Operating System: MacOS Sonoma 14.6.1
- Browser: Google Chrome
- Version: 2.14.3

**Comment by jooyoungseo** [comment]
Closed via #528
