### ISSUE TITLE
Boxplot: focus moving is unstable

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#54]
When navigating a stat vertically across groups, sometimes focus goes to another stat category.

## Reproducible Steps

1. Open boxplot.html

1. Focus on low (AKA minimum) of "suv"

1. Keep pressing down-arrow keys (autoplay does not have this issue so please test with manual arrow keys).

1. If you reached the low of "2seater" without any issues, keep pressing up-arrow multiple times to go back to the suv low.

1. Repeat this up and down round trip multiple times: you may notice that your focus sometimes moves to lower outlier group out of the blue.

**Comment by ellvix** [comment]
Can't quite reproduce this well, but I see it if I move really chaotically. There was a related but that's been on my list that might be the cause though; I wasn't locking position to within the plots. Fixed that and now I can't get this issue at all, so I'll call it fixed.
