### ISSUE TITLE
fix(lineplot): address an issue where autoplay does not work

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#542]
I don't know whether this is an inadvertent regression. Sonification autoplay does not work. Test the following:

1. Open https://xabilitylab.ischool.illinois.edu/maidr/galleries/lineplot.html

2. Tab to the interactive plot area

3. Press autoplay key (ctrl+shift+RightArrow on Windows; cmd+shift+RightArrow on Mac)

## Current Behavior

Sonification autoplay does not work at all.

## Expected Behavior

Sonification autoplay should work as intended.

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by krishnanand5** [comment]
Issue is seen only on the publicly available demo plot whereas the issue cannot be reproduced on my local project repo. Going by the commit log on my local, I have the same codebase as **2.14.8** release, have we had any other releases after this one Professor @jooyoungseo ?
