### ISSUE TITLE
fix(scatterplot): address an issue where the sonification autoplay does not work in the second layer

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#543]
This might be another inadvertent regression. Sonification autoplay does not work in the second layer of a scatter plot. Test the following:

1. Open https://xabilitylab.ischool.illinois.edu/maidr/galleries/scatterplot.html

2. Tab to the interactive plot area

3. Press PageUp to switch to the smooth layer

4. Press autoplay key (ctrl+shift+RightArrow on Windows; cmd+shift+RightArrow on Mac)

## Current Behavior

Sonification autoplay does not work at all.

## Expected Behavior

Sonification autoplay should work as intended.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by krishnanand5** [comment]
Issue seen only on the publicly available demo plot but not seen on my local project repo, which going by my commit log is running the same code as release **2.14.8**. There is an error caught on the web devtools when the control is switched to the smoothed layer and autoplay is initiated - captured in the attached screenshot:
[
<img width="1710" alt="Screenshot 2024-09-03 at 6 52 12 PM" src="https://github.com/user-attachments/assets/a99d0431-07bb-4156-a47e-005d253401ec">
](url)
