### ISSUE TITLE
fix(histogram): address an issue where replaying the current data point with Spacebar does not work

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#544]
Replaying the current data point with Spacebar doesn't work in histograms:

## Repros

1. Open https://xabilitylab.ischool.illinois.edu/maidr/galleries/histogram.html

1. Tab to the interactive plot area

1. Navigate any data point with arrow keys

1. Press Spacebar to see if it replays the focused data point

## Current  Behavior

Replaying doesn't work

## Expected Behavior

Spacebar needs to trigger replaying the currently focused data point

**Comment by ellvix** [comment]
Can't replicate, @jooyoungseo can you see if you still have this issue?

**Comment by jooyoungseo** [comment]
@ellvix Yes, the issue still exits:

When Spacebar is pressed, Sonification gets replayed. However, the aria-live event is not fired again. It just holds the old one, which means JAWS/NVDA doesn't announce the Text announcement. This does not happen in other plots, such as bar plot.
