### ISSUE TITLE
Shinyapps has issues with boxplot not showing all points in braille mode

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#546]
See https://xabilitylab.shinyapps.io/plot_tutorial/, look at boxplot. You'll notice that the boxplots are missing data, like missing the left whisker.

**Comment by ellvix** [comment]
Can't duplicate. All plots on that URL look fine to me and behave perfectly. I didn't test all functions, just basic movement to look for missing data, but nothing was missing.

**Comment by jooyoungseo** [comment]
Have you tested braille mode? We had an issue with the box plot braille, especially please test it again in the shiny example.

**Comment by ellvix** [comment]
All issues are with braille mode on, and with skewed charts. Issues: 
- Positively skewed: Braille on, once you go to upper outliers you're stuck
- Positively skewed: no max
- Neg skewed: get stuck on 25%, can't go lower
