### ISSUE TITLE
Work on new (no jittered) scatterplot svg

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#56]
@yujuny2 -- I have just uploaded the following scatterplot SVG:

1. [scatterplot/scatterplot_no_jitter_point_only.svg](https://github.com/uiuc-ischool-accessible-computing-lab/accessible-graph/blob/main/scatterplot/scatterplot_no_jitter_point_only.svg)

1. [scatterplot/scatterplot_no_jitter_with_bestfit.svg](https://github.com/uiuc-ischool-accessible-computing-lab/accessible-graph/blob/main/scatterplot/scatterplot_no_jitter_with_bestfit.svg)

Please work on these files instead of the old one because these did not use jitter noise. The only difference between 1. and 2. is whether there is an added best line or not.

FYI, the backend raw data that I previously provided in json format as well as HTML are still valid because I created them without jitter noise at that time. I guess this no jittered SVGs would be more similar to the raw data.

**Comment by jooyoungseo** [comment]
@yujuny2 -- As discussed today, I have added new SVG file having smoothed curve instead of the straight best fit line. Please use [scatterplot/scatterplot_no_jitter_with_loess_curve.svg](https://github.com/uiuc-ischool-accessible-computing-lab/accessible-graph/blob/255e383beb3cdc88c2662b9d308cb43dfe013292/scatterplot/scatterplot_no_jitter_with_loess_curve.svg).

**Comment by yujuny2** [comment]
Updated scatterplot.html with smooth curved svg file.
