### ISSUE TITLE
feat: activate maidr plot against onclick event

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#566]
Currently, users have to press Tab key in order to activate maidr plot. We also want to activate it when the visual plot is clicked. This is important because screen reader users also need to press Enter key on an SVG object while navigating in virtual cursor to activate it. Pressing Enter key in virtual cursor triggers onclick event.

**Comment by ellvix** [comment]
This already works because of the tabindex="0" on the chart.
