### ISSUE TITLE
feat: provide alt-text for maidr plot

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#567]
We need to add alt-text to maidr plot. By default, we can use the title property and some additional instructions on how to activate it.

**Comment by ellvix** [comment]
Get specific text from https://github.com/xability/maidr/commit/65254ac3c4c09eb60f1585aa297d50b87911abd9#diff-38a270adae08b8446c7ae48042fdfa22094c426a96904b5c87879aefa1b54e54R123
