### ISSUE TITLE
Number of outlier: indicate number consistenly

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#61]
1. When the number of outliers is 1, the current method is just omitting the number; however, please indicate the number like below:

> 1 Lower Outlier 126.18

1. For empty outliers, please do the following:

> 0 Out Lier

**Comment by jooyoungseo** [comment]
@ellvix Thanks for doing this! As I discussed above, would you mind making the empty outlier as "0 outlier"? There is a special reason why I persist this consistency even for empty outlier. I can demonstrate this cognitive burden when we meet.

> 1. For empty outliers, please do the following: 
> 
> 0 Out Lier

**Comment by ellvix** [comment]
Should be fixed now, there was a bug in detecting whether or not we were doing text display for an outlier. 

If it still doesn't work @jooyoungseo can you correct how each text section should display? Preferably in the design doc, I assigned you an area.
