### ISSUE TITLE
Mac controls and a switcher condition

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#62]
Add Command + key for mac, mirror current Ctrl + key for PC controls. 

Try using `navigator.userAgent` or `navigator.platform` to detect OS and switch both controls for all plots, and key control info on help menu.

**Comment by jooyoungseo** [comment]
Related to #52

**Comment by yujuny2** [comment]
Added mac controls. Command is used for mac instead of Ctrl. Ctrl is used for all other OS.
