### ISSUE TITLE
Smooth audio

### ISSUE THREAD

**Issue by ellvix** [xability/maidr-legacy#63]
Investigate smooth audio for scatterplot curve. Try `AudioParam.setValueCurveAtTime()`

**Comment by jooyoungseo** [comment]
FYI, I have uploaded [a smoothed curve to the scatter plot](https://github.com/uiuc-ischool-accessible-computing-lab/accessible-graph/blob/255e383beb3cdc88c2662b9d308cb43dfe013292/scatterplot/scatterplot_no_jitter_with_loess_curve.svg).
