### ISSUE TITLE
Add reverse autoplay direction keys

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#65]
1. Alt+Shift+Left-Arrow: From the beginning to the current position.

1. Alt+Shift+Right-Arrow: From the end to the current position.

**Comment by yujuny2** [comment]
Added this feature to all plots.

**Comment by jooyoungseo** [comment]
@yujuny2 -- I don't think this has been fixed yet. Still cannot use Alt+Shift+Left-Arrow or Alt+Shift+Right-Arrow key for reverse autoplay.

**Comment by yujuny2** [comment]
@jooyoungseo I'm not sure what's wrong because it works for me on both windows and mac. Is that applicable for all the plots or certain plot? Does it not work at all or the audio is played in a wrong way?

**Comment by jooyoungseo** [comment]
@yujuny2  -- Now it works. However, it does not work in the second layer (smoothed line) in scatterplot.

**Comment by jooyoungseo** [comment]
@yujuny2 also Ctrl+Right-Arrow (going to the far right position) does not work in scatterplot after your recent patches.

**Comment by yujuny2** [comment]
@jooyoungseo -- There's a small bug. It's fixed.

**Comment by jooyoungseo** [comment]
@yujuny2  Awesome! This works mostly only except for the following condition: reverse sonification panning does not work in the smoothed line layer.

## Reproducible Steps

1. In the first layer of `scatterplot.html`, press Ctrl+RightArrow to go to the far right point: "7, [24]".

1. Switch to the second layer (smoothed line) and press Ctrl+Shift+LeftArrow to trigger outgooing autoplay to the left from the current position.

## Bug

Currently, the sound panning is played from left to right.

## Expected Behavior

Sound needs to be played from right to left when Ctrl+Shift+LeftArrow is pressed. In the same way, Alt+Shift+RightArrow needs to play sonification from right to left.

**Comment by yujuny2** [comment]
@jooyoungseo I think the panning works correctly now. I have also added a new sonification mode to the point layer, and other controls to the scatterplot's braille display. 

Currently, the x positions in both layers are not synced because both have different number of points. I'm working on having two different x positions in two different layers instead of syncing them. I wonder what you think about this.

**Comment by jooyoungseo** [comment]
@yujuny2  

1. The reverse autoplay works nicely! Thank you so much!

2. I agree with your ideas about separating the two layer points instead of syncing them together because they have different number of points.
