### ISSUE TITLE
Making boxplot accessible

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#7]
* Boxplot definition: https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/box-whisker-plots/a/box-plot-review

- [ ] Up and down arrow keys move between different boxplot groups.

- [ ] Left and right arrow keys move section by section within selected boxplot.

I will add thorough description on the system design soon.

**Comment by ellvix** [comment]
These controls are implemented, but now we're adding more haha
