### ISSUE TITLE
General autoplay bug: current position is always triggered in text mode

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#74]
In any graphs and in any position, press CMD+Shift+LeftArrow or CMD+Shift+RightArrow to start autoplay.

When autoplay is on, text  mode needs to be muted so that our users only hear the sonification sound. However, autoplay triggers the current position in text output. Please turn off the text mode as soon as the autoplay key is pressed and turn it on again right after the autoplay is finished.

**Comment by jooyoungseo** [comment]
@yujuny2 -- Thanks for working on this issue. I have found another inadvertent regression that needs to be fixed.

## Reproducible Steps

1. Open boxplot.html

1. Press arrow keys to go to upper outlier area of suv.

1. Hit Ctrl+Shift+Left-Arrow (CMD+Shift+Left-Arrow on Mac) to autoplay to the left: The sonification starts from high of suv instead of the current outlier position.

This needs to be fixed to trigger the current position in sonification: We only want to turn off the current position text, not the sonification.

**Comment by yujuny2** [comment]
@jooyoungseo -- I've fixed this. I think it's working like what you've mentioned.

**Comment by jooyoungseo** [comment]
Great! Thanks! @yujuny2!
