### ISSUE TITLE
Implement sound volume weight

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#76]
I have finally been able to do reverse-engineering jobs to obtain the real data for both point and smoothed line layers within scatter plot. Please use the following data for scatter plot.

1. Point layer (I know you already used the raw data for point values, but this is the exact one. Please replace): [scatterplot/layers/point_layer.json](https://github.com/uiuc-ischool-accessible-computing-lab/accessible-graph/blob/main/scatterplot/layers/point_layer.json)

1. Smoothed line layer: [scatterplot/layers/smooth_layer.json](https://github.com/uiuc-ischool-accessible-computing-lab/accessible-graph/blob/main/scatterplot/layers/smooth_layer.json)

Please note: if there are multiple values on the same spot, use the larger volume to indicate the weight. For example, let's say there are x: 2, y: 4 and x: 2, y: 4 (the same values on the same spot). Sighted people would see them thicker, but blind people cannot see them. Therefore, please use larger volume parameter as a way of weighted value.

**Comment by yujuny2** [comment]
@jooyoungseo -- Just for your information, from my observation, I actually don't see the spot as bigger when there are two points at the same position. Both spots just overlap and appear as one point. Should we still highlight the points with thicker volume?

**Comment by jooyoungseo** [comment]
@yujuny2  -- Actually, that's because I did not provide any visual weight parameter when creating this ggplot object. I can fix the visual thickness later. Even though you don't see the weight in thicker (or bigger) points, please implement sound volume weight.
