### ISSUE TITLE
Move all the keydown events to svg-level instead of the whole document

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#79]
I know there is a tradeoff, but please bind all the keydown events to svg units instead of the whole document. Because we will likely embed more than one graph on the same page and the document-level key bindings can cause some issues. We may want to isolate them within an SVG object.

**Comment by ellvix** [comment]
Everything except LogTracker, and kill autoplay (ctrl). These can stay global, and when we publish after doing research we'll remove LogTracker
