### ISSUE TITLE
Autoplay has about one second lag

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#80]
Autoplay response speed is a little bit slow. I think there is about one second lag to respond after pressing autoplay keys (Ctrl+Shift+LeftArrow or Ctrl+Shift+RightArrow). We may want to make the response rate faster.

**Comment by ellvix** [comment]
same issue as #210, JAWS just has a 1 sec delay with all controls

**Comment by ellvix** [comment]
closed as it's not reproducible, along with #210
