### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by yilinxia** [xability/maidr-legacy#83]
Test System: 
* macOS Monterey Version 12.6
* Windows 10 Pro

Based on my test, our system works properly on Chrome (Version 109.0.5414.87) , Microsoft Edge (Version 109.0.1518.55) and Firefox 109.0 (64-bit), Safari Version 16.0 (17614.1.25.9.10, 17614) 

However, when I tested a few hours ago, it didnot work for Safari and Firefox. And here is the error message I received

<img width="487" alt="image" src="https://user-images.githubusercontent.com/24869900/213061157-61ab370c-8193-46e6-879e-fc9534c55424.png">

**Comment by yujuny2** [comment]
@yilinxia I have pushed new commits just now. Can you check again to see if it's working on Firefox?

**Comment by yilinxia** [comment]
@yujuny2 it works. Thank you!
