### ISSUE TITLE
Mismatch between Braille and Numberical Values

### ISSUE THREAD

**Issue by yilinxia** [xability/maidr-legacy#94]
I found there is a mismatch for bar plot between the values and the braille characters, maybe we used a different method… take our bar plot as an example, based on my understanding, the normalized result of [42.12, 128.34, 316.07, 360.78, 563.78] shall be [0.0, 0.17, 0.53, 0.61, 1.0], which should be ⣀⣀⠒⠒⠉. However, right now, ⣀⣀⠤⠒⠉

**Comment by yujuny2** [comment]
Fixed barplot's braille.
