### ISSUE TITLE
[Boxplot] Ctrl+DownArrow does not go to the last item

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#95]
@ellvix In boxplot, try with Ctrl+DownArrow key. It does not go to the last item at the bottom.

**Comment by ellvix** [comment]
Can't reproduce, works as intended. Maybe the intention is wrong? Currently the idea is to Ctrl + Up or Down brings you to the top or bottom, but keeps your horizontal position the same. So if I'm in the middle on a 50% and hit Ctrl + Down, I'll be at the bottom and still on the 50%.

**Comment by jooyoungseo** [comment]
@ellvix -- Still having this issue.

## Reproducible Steps

1. Locate your cursor at 25% of suv class.

1. Press Ctrl+DownArrow: it goes to subcompact group instead of 2seater.

**Comment by jooyoungseo** [comment]
Aw, I found the reason. It just does not work for JAWS. Something interrupts the Ctrl+Up/DownArrows on JAWS end. NVDA works fine. This is not our system issue.
